cab/urls.py
from django.conf.urls import url, patterns, include
from django.contrib.auth import views as auth_views
import cab.views

urlpatterns = patterns('',
                       # ex: /cab Klients/
                       url(r'^$', cab.views.main, name="cab.main"),
    url(r'^downloadAvatar/$', cab.views.downloadAvatar, name="cab.downloadAvatar"),
    url(r'^downloadFilesNewItem/$', cab.views.downloadFilesNewItem, name="cab.downloadFilesNewItem"),
    url(r'^saveAvatar/$', cab.views.saveAvatar, name="cab.saveAvatar"),
    url(r'^editProfile/$', cab.views.editProfile, name="cab.editProfile"),
    url(r'^addItem/$', cab.views.addItem, name="cab.addItem"),
    url(r'^registerPost/$', cab.views.registerPost, name="cab.registerPost"),
    url(r'^deleteItem/$', cab.views.deleteItem, name="cab.deleteItem"),
    url(r'^addDownloadFile/$', cab.views.addDownloadFile, name="cab.addDownloadFile"),
    url(r'^addDownloadFileAll/$', cab.views.addDownloadFileAll, name="cab.addDownloadFileAll"),
    url(r'^search/$', cab.views.search, name="search"),
    url(r'^like/$', cab.views._like, name="like"),
    url(r'^ajaxOpens/$', cab.views.ajaxOpens, name="ajaxOpens"),
    url(r'^changePassword/$', cab.views.changePassword, name="cab.changePassword"),
    url(r'^change/$', cab.views.changeItem, name="cab.changeItem"),
    url(r'^changeDelFoto/$', cab.views.changeDelFoto, name="cab.changeDelFoto"),
    url(r'^changeAddFoto/$', cab.views.changeAddFoto, name="cab.changeAddFoto"),
    url(r'^changeTags/$', cab.views.changeTags, name="cab.changeTags"),
    url(r'^changeLibrary/$', cab.views.changeLibrary, name="cab.changeLibrary"),
    url(r'^changeInform/$', cab.views.changeInform, name="cab.changeInform"),
    url(r'^changeDelFile/$', cab.views.changeDelFile, name="cab.changeDelFile"),
    #url(r'^changeAddFile/$', cab.views.changeAddFile, name="cab.changeAddFile"),
    url(r'^changeAddFileSave/$', cab.views.changeAddFileSave, name="cab.changeAddFileSave"),
)

staff/urls.py
from django.conf.urls import url
from staff import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login$', views.staff_login, name='staff-login'),
    url(r'^item$', views.item_view, name='item'),
    url(r'^item/(?P<pk>\d+)$', views.item_view_only, name='item_view_only'),
    url(r'^item/item_delete$', views.item_delete, name='item_delete'),
    url(r'^item/item_image_delete$', views.item_image_delete, name='item_image_delete'),
    url(r'^item/item_file_delete$', views.item_file_delete, name='item_file_delete'),
    url(r'^edit-profile/(?P<pk>\d+)$',
        views.edit_profile, name='edit-profile'),
    url(r'^user-info/$',
        views.user_info, name='user-info'),
    url(r'^change-password/$',
        views.change_password, name='change-password'),
    url(r'^change_avatar/(?P<user_id>\d+)/$',
        views.saveAvatar, name='saveavatar'),
    url(r'^categories$', views.categories, name='categories'),
    url(r'^categories-edit/(?P<pk>\d+)$', views.categories_edit, name='categories-edit'),
    url(r'^libraries$', views.libraries, name='libraries'),
    url(r'^libraries-edit/(?P<pk>\d+)$', views.libraries_edit, name='libraries-edit'),
    url(r'^addlibraries$', views.addlibraries, name='addlibraries'),
    url(r'^editlibraries/(?P<id>\d+)$', views.editlibraries, name='editlibraries'),
]

testSite.1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
import cab.views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dashboard.urls')),
    url(r'^profile/', include('cab.urls')),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^statistic/', include('statistic.urls')),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'},
                           name='auth_login'),
    url(r'^logout/$', cab.views.cab_logout, name='auth_logout'),
    url(r'^register/$', cab.views.register, name='auth_register'),
    url(r'^about/$', include('about.urls'))
]

testSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
import cab.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dashboard.urls')),
    url(r'^profile/', include('cab.urls')),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^statistic/', include('statistic.urls')),
    url(r'^admins/', include('staff.urls', namespace="staff")),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'},
                           name='auth_login'),
    url(r'^logout/$', cab.views.cab_logout, name='auth_logout'),
    url(r'^register/$', cab.views.register, name='auth_register'),
    url(r'^forgot/$', cab.views.forgotPassword, name='auth_forgotPassword'),
    url(r'^about/$', include('about.urls')),
]

staff/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

staff/forms.py
from catalog.models import Libraries
from django import forms


class LibrariesForm(forms.ModelForm):
    class Meta:
        model = Libraries
        fields = ['name', 'image']

staff/views.py
from django.shortcuts import render
from cab.models import ExtUser
from catalog.models import item, Categories, Libraries
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404
from PIL import Image


# Create your views here.
# @staff_member_required(login_url='/admins/login')
def home(request):
    if request.user.is_authenticated():
        if request.user.is_admin:
            users = ExtUser.objects.all()
            item_all = item.objects.all()
            delete_id = request.GET.get('delete_id')
            if delete_id:
                try:
                    ExtUser.objects.get(id=delete_id).delete()
                    return HttpResponseRedirect(reverse('staff:home'))
                except:
                    return HttpResponseRedirect(reverse('staff:home'))
            make_staff = request.GET.get('make_staff')
            if make_staff:
                extuser = get_object_or_404(ExtUser, id=make_staff)
                extuser.is_admin = True
                extuser.save()
            remove_staff = request.GET.get('remove_staff')
            if remove_staff:
                extuser = get_object_or_404(ExtUser, id=remove_staff)
                extuser.is_admin = False
                extuser.save()
            return render(request, 'home.html', {"users": users, "item_all": item_all})
        else:
            return render(request, 'staff-login.html')    
    else:
        return render(request, 'staff-login.html')
    
def staff_login(request):
    if request.method == 'POST':
        username_email = request.POST['username']
        password = request.POST['password']
        user = authenticate(email=username_email, password=password)
        if user is not None:
            if user.is_active:
                if user.is_admin:
                    login(request, user)
                    return HttpResponseRedirect(reverse('staff:home'))
                else:
                    messages.warning(request, "Sorry you Don't have access to Enter to this page , please contact the website administrator .")
                    return render(request, 'staff-login.html')
            else:
                messages.warning(request, 'Your account locked')
                return render(request, 'staff-login.html')                
        else:
            messages.warning(request, 'Please Enter valid username / password .')
            return render(request, 'staff-login.html')
    return render(request, 'staff-login.html')

@staff_member_required(login_url='/admins/login')
def edit_profile(request, pk):
    if request.method == 'POST':
        user_id = request.POST['user_id']
        ExtUser.objects.get(id=user_id).delete()
        return HttpResponseRedirect(reverse('staff:home'))
    user = ExtUser.objects.get(id=pk)
    items = item.objects.filter(user_id=request.user.id).select_related()
    return render(request, 'edit-profile.html', {"user": user, "items": items})


@staff_member_required(login_url='/admins/login')
def user_info(request):
    if request.method == 'POST':
        user = ExtUser.objects.get(email=request.POST['p_email'])
        user.firstname = request.POST['firstName']
        user.lastname = request.POST['lastname']
        user.email = request.POST['email']
        user.save()
        return HttpResponseRedirect(reverse('staff:edit-profile', args=[user.id]))

@staff_member_required(login_url='/admins/login')
def change_password(request):
    user = ExtUser.objects.get(id=request.POST['user_id'])
    user.set_password(request.POST['password2'])
    user.save()
    return JsonResponse({'result':True})

@staff_member_required(login_url='/admins/login')
def saveAvatar(request, user_id):
    user = ExtUser.objects.get(id=user_id)
    user.avatar = request.POST['name'].replace('media', 'static')
    user.save()
    return HttpResponse("ok")

from catalog.models import item, fotos, file, like

@staff_member_required(login_url='/admins/login')
def item_view(request):
    items = item.objects.all().order_by('-date_published')
    download = False
    if items.count() > 12:
        download = True
    lik = []
    items = items[:12]
    for i in items:
        lik.append([i.id, like.objects.filter(item=i).count()])
    return render(
        request, 'staffitems.html',
        {'items': items, 'likes': lik, 'download': download})


@staff_member_required(login_url='/admins/login')
def item_view_only(request, pk):
    libraries_all = Libraries.objects.all()
    if request.method == 'POST':
        it = item.objects.get(id=pk)
        library = Libraries.objects.get(name=request.POST['library'])
        it.name = request.POST['name']
        it.information = request.POST['information']
        it.tags = request.POST['tags']
        it.library = library
        it.save()
        return HttpResponseRedirect(reverse("staff:item_view_only", args=[pk]))
    id = request.path[request.path.find('/')+1:]
    id = id[id.find('/')+1:]
    id = id[:id.find('/')]
    it = item.objects.select_related().get(id=int(pk))
    it.views += 1
    it.main_foto.name = it.main_foto.name.replace('media/','static/')
    it.save()
    #i.main_foto.save()
    f = it.foto.replace('media','static').split(';')
    files = file.objects.select_related().filter(item=it)
    for i in files:
        i.f.name = i.f.name.replace('media/', 'static/')
        #i.f.save()
        
    lik = like.objects.filter(item=it).count()
    #tags = it.tags
    return render(request, 'staff-item-view.html', {
        'item':it,
        'f':f[:len(f)-1],
        'files': files,
        'like': lik,
        'tags':it.tags.split(';'),
        'libraries_all': libraries_all,
    })

@staff_member_required(login_url='/admins/login')
def item_image_delete(request):
    _item = item.objects.select_related().get(id=int(request.POST['item'])) 
    if request.user.is_staff:
        if int(request.POST['number']) != 1:
            q = _item.foto.split(';')[int(request.POST['number'])-1]
            _item.foto = _item.foto.replace(q+';', '')
            _item.save()
            return HttpResponse('ok')
        else:
            _item.foto = _item.foto[_item.foto.find(':')+1:]
            f = _item.foto.split(';')[0].replace('static/','media/')
            img = Image.open(f)
            if (img.width / 4.0) * 3 != img.height:
                if img.width > img.height:
                    one = img.height / 3.0
                    img = img.crop(
                        (
                            (img.width - one*4)/2.0,
                            0,
                            (img.width - one*4)/2.0 + one*4.0,
                            one*3.0
                        )
                    )
                else:
                    one = img.width / 4.0
                    img = img.crop(
                        (
                            0,
                            (img.height - one*3)/2.0,
                            one*4,
                            (img.height - one*3)/2.0 + one*3.0
                        )
                    )
                img.save(f)
            fot = fotos(path=f, name=f.replace('media/','static/'))
            fot.save()
            _item.main_foto = fot
            
            _item.save()
            
            return HttpResponse('ok')
    else:
        raise Http404

@staff_member_required(login_url='/admins/login')
def item_file_delete(request):
    _item = item.objects.get(id=int(request.POST['item']))
    if request.user.is_staff:
        f = file.objects.get(id=int(request.POST['id']))
        if f.item == _item:
            f.delete()
            return HttpResponse('ok')
    raise Http404


@staff_member_required(login_url='/admins/login')
def item_delete(request):
    item_id = request.GET.get('item_id')
    if item_id:
        item.objects.get(id=item_id).delete()
    return HttpResponseRedirect(reverse('staff:home'))
    

@staff_member_required(login_url='/admins/login')    
def categories(request):
    if request.method == 'POST':
        obj = Categories()
        obj.name = request.POST['name']
        obj.url = request.POST['url']
        obj.save()
        return HttpResponseRedirect(reverse('staff:categories'))
    delete_id = request.GET.get('delete_id')
    if delete_id:
        try:
            Categories.objects.get(id=delete_id).delete()
            return HttpResponseRedirect(reverse('staff:categories'))
        except:
            return HttpResponseRedirect(reverse('staff:categories'))
    categories_all = Categories.objects.all()
    return render(request, 'category.html', {"categories_all": categories_all})
    
    
def categories_edit(request, pk):
    if request.method == 'POST':
        obj = Categories.objects.get(id=pk)
        obj.name = request.POST['name']
        obj.url = request.POST['url']
        obj.save()
        return HttpResponseRedirect(reverse('staff:categories'))
    categories = Categories.objects.get(id=pk)
    return render(request, 'categories-edit.html', {"categories": categories})


@staff_member_required(login_url='/admins/login')    
def libraries(request):
    delete_id = request.GET.get('delete_id')
    if delete_id:
        try:
            Libraries.objects.get(id=delete_id).delete()
            return HttpResponseRedirect(reverse('staff:libraries'))
        except:
            return HttpResponseRedirect(reverse('staff:libraries'))
    libraries_all = Libraries.objects.all()
    return render(request, 'library.html', {"libraries_all": libraries_all})


@staff_member_required(login_url='/admins/login')
def libraries_edit(request, pk):
    libraries = Libraries.objects.get(id=pk)
    return render(request, 'libraries-edit.html', {"libraries": libraries})

staff/templates/library.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block mycss %}
<link rel="stylesheet" href="{% static 'css/profile.css'%}">
<script src="{% static 'cab/js/tags/bootstrap-tagsinput.js'%}"></script>
{% endblock %}

{% block header %}
<header>
	<div class="container" style="padding:0px">
		<div class="row">
			<a href="/" class="logo">
			    <img src="{% static 'images/logo.png'%}" alt="" />
			 </a>
            <div class="home-banner-inner col-sm-3" style="padding:0px; margin-left:10px">
    			<form role="search" class="form-search" method="get" id="searchform" action="{% url 'search' %}">
            		<div class="input-group">
            			<input style="height:inherit;width:100%" type="text" class="form-control" placeholder="Enter a Search Item" value="" name="s" id="s">	
            			<span class="input-group-btn">
            				<button style="height:100%" type="submit" class="banner-btn btn-append"><i class="fa fa-search fa- "></i></button>
            			</span>
            			<input type="hidden" value="incsub_wiki" name="post_type" id="post_type">
            		</div>
            	</form>
        	</div>
			<ul id="menu-test" class="mainNav">
			    <li id="menu-item-7" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
    			    <a href="{% url "staff:home" %}">
    			        Users
    		        </a>
    	        </li>
                <li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                    <a href="{% url "staff:item" %}">
                        Items
                    </a>
                </li>
                <li id="menu-item-8" class="first-menu-item menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-7">
                    <a href="{% url "staff:categories" %}">
                        Categories
                    </a>
                </li>
                <li id="menu-item-8" class="first-menu-item menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-7">
                    <a href="{% url "staff:libraries" %}">
                        Libraries
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                    <a href="/logout">
                        logout
                    </a>
                </li>
                {% else %}
                <li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                    <a href="/login">Join / Sign in</a>
                </li>
                {% endif %}
            </ul>
			<button id="showLeft"><i class="fa fa-bars open-nav"></i> <i class="fa fa-times close-nav"></i></button>
			<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left mobile" id="cbp-spmenu-s1">
				<h3>Menu</h3>
				<ul id="menu-test-1" class="mobileNav">
				    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
				        <a href="/">
				            dashboard
			            </a>
		            </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                        <a href="/catalog">
                            EXPLORE
                        </a>
                    </li>
                    <li class="first-menu-item menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-7">
                        <a href="/about">
                            About us
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                        <a href="/profile">
                            Profile / Items
                        </a>
                    </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                        <a href="/logout">
                            logout
                        </a>
                    </li>
                    {% else %}
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                        <a href="/login">Join / Sign in</a>
                    </li>
                    {% endif %}
                </ul>			
            </nav>
			
		</div>
	</div>
</header>
{% endblock %}

{% block content %}
<div class="container">
    <div class="col-md-2 well" style="margin-top: 10px; margin-right:25px;">
        <div class="sidebar-nav">
            <ul id="menu-test" class="mainNav">
			    <li id="menu-item-7" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
    			    <a href="{% url "staff:home" %}">
    			        Users
    		        </a>
    	        </li>
                <li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                    <a href="{% url "staff:item" %}">
                        Items
                    </a>
                </li>
                <li id="menu-item-8" class="first-menu-item menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-7">
                    <a href="{% url "staff:categories" %}">
                        Categories
                    </a>
                </li>
                <li id="menu-item-8" class="first-menu-item menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-7">
                    <a href="{% url "staff:libraries" %}">
                        Libraries
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                    <a href="/logout">
                        logout
                    </a>
                </li>
                {% else %}
                <li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                    <a href="/login">Join / Sign in</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="col-md-8">
      <table class="table">
          <tbody>
              {% for libraries in libraries_all %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td><p style="margin-bottom: 0px;margin-left: 62px;font-size: 32px;">{{ libraries }}</p></td>
                <!--<a style="line-height: 1em;height:initial" data-id="79" href="{% url "staff:edit-profile" user.id %}" class="btn edit"><i class="fa fa-pencil "></i></a>-->
                <td><a href="{% url "staff:libraries" %}?delete_id={{ libraries.id }}" style="line-height: 1em;height:initial;width: 111px;" class="btn"><i class="fa fa-pencil "></i> Delete</a></td>
                <td><a href="{% url "staff:libraries-edit" libraries.id %}" style="line-height: 1em;height:initial;width: 111px;" class="btn"><i class="fa fa-pencil "></i> Edit</a></td>
              </tr>
              {% endfor %}
        </tbody>
    </table>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="container">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <hr>
        <button style="line-height: 1em;height:initial" class="btn btn-info" type="button" data-toggle="modal" data-target="#addCat">Add</button>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="modal fade" id="addCat" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="addCatModalLabel">Add new Library?</h4>
      </div>
      <div class="modal-body">
        <form class="form-horizontal form-label-left" method="POST" action="">
            {% csrf_token %}
            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Name <span class="required">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <input type="text" id="name" required="required" class="form-control col-md-7 col-xs-12" placeholder="Name of library">
              </div>
            </div>

           
            <input type="hidden" name="fotos" id="fotos_inputAdd" />
        </form>
        
        <form class="dropzoneAddImage dropzone form-horizontal form-label-left" method="POST">
            {% csrf_token %}
        </form>
        
          <p class="errors" style="color:red"></p>
      </div>
      <div class="modal-footer">
        <button style="display:inline-block; height: 3em; padding: 0px 10px;" type="button" class="btn btn-default" data-dismiss="modal">End</button>
        <button style="display:inline-block; height: 3em; padding: 0px 10px;" type="button" class="btn btn-primary submit">Yes</button>
      </div>

    </div>
  </div>
</div>
<script type="text/javascript" src="{% static 'cab/js/dropzone/dropzone.js'%}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js'%}"></script>
  <!--<script type="text/javascript" src="{% static 'cab/js/cropping/cropper.min.js'%}"></script>
  <script type="text/javascript" src="{% static 'cab/js/cropping/main2.js'%}"></script>-->
<script type="text/javascript">

$(function() {
    var myDropzone2 = new Dropzone(".dropzoneAddImage", {
        url: "{% url 'cab.downloadAvatar' %}",
        dictDefaultMessage: 'Drop image here to upload(one image is allowed)',
        acceptedFiles: 'image/*'

    });
    //croppImage.replace($('#inputImage').val());
    myDropzone2.on("success", function(file, request){
        /*if($('#fotos_inputAdd').val() == "")
        {
            $('#addCat').modal('hide');
            $('#cropperImgModal #inputImage').val('/' + request.foto.replace('media/','static/'));
            $('.cropper-container > img').attr('src', $('#inputImage').val());
            $('.cropper-cropbox > span.cropper-viewer img').attr('src', $('#inputImage').val());
            
            $('#cropperImgModal').modal('show');
        }
        else
        {*/
            $('#fotos_inputAdd').val(
                $('#fotos_inputAdd').val() + request.foto + ";"  
            );
        //}
        
    });
    myDropzone2.on("error", function(file){
        this.removeFile(file);
        alert("Error download");
    });

    $('#addCat button.submit').click(function() {
        if( ($('#name').val() == "") )
            alert("Please fill in the fields");
        //else if ( $('#fotos_inputAdd').val() == "" )
        //    alert("Please Download images");
        else{
            $.ajax({
              url: "{% url 'staff:addlibraries' %}",
              type: 'POST',
              data: {
                  name: $('#name').val(),
                  fotos: $('#fotos_inputAdd').val(),
              },
              success: function(data){
                  window.location.href = "{% url 'staff:libraries' %}";
              },
              error: function(data) {
                  alert('ERROR!');
              },            
              // CSRF механизм защиты Django
                beforeSend: function(xhr, settings) {
                console.log('-------------before send--');
                  function getCookie(name) {
                      var cookieValue = null;
                      if (document.cookie && document.cookie != '') {
                            var cookies = document.cookie.split(';');
                            for (var i = 0; i < cookies.length; i++) {
                                var cookie = jQuery.trim(cookies[i]);
                                // Does this cookie string begin with the name we want?
                            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                break;
                            }
                        }
                    }
                    return cookieValue;
                    }
                    if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                        // Only send the token to relative URLs i.e. locally.
                        xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                    }
                }
            });// ajax
        }
    });
});
</script>
{% endblock %}