about/urls.py
from django.conf.urls import patterns, url
from about import views

urlpatterns = patterns('',
                       # ex: /cab Klients/
                       url(r'^$', views.main, name='about_main'))

cab/urls.py
from django.conf.urls import url, patterns, include
from django.contrib.auth import views as auth_views
import cab.views

urlpatterns = patterns('',
                       # ex: /cab Klients/
                       url(r'^$', cab.views.main, name="cab.main"),
    url(r'^downloadAvatar/$', cab.views.downloadAvatar, name="cab.downloadAvatar"),
    url(r'^downloadFilesNewItem/$', cab.views.downloadFilesNewItem, name="cab.downloadFilesNewItem"),
    url(r'^saveAvatar/$', cab.views.saveAvatar, name="cab.saveAvatar"),
    url(r'^editProfile/$', cab.views.editProfile, name="cab.editProfile"),
    url(r'^addItem/$', cab.views.addItem, name="cab.addItem"),
    url(r'^registerPost/$', cab.views.registerPost, name="cab.registerPost"),
    url(r'^deleteItem/$', cab.views.deleteItem, name="cab.deleteItem"),
    url(r'^addDownloadFile/$', cab.views.addDownloadFile, name="cab.addDownloadFile"),
    url(r'^addDownloadFileAll/$', cab.views.addDownloadFileAll, name="cab.addDownloadFileAll"),
    url(r'^search/$', cab.views.search, name="search"),
    url(r'^like/$', cab.views._like, name="like"),
    url(r'^ajaxOpens/$', cab.views.ajaxOpens, name="ajaxOpens"),
    url(r'^changePassword/$', cab.views.changePassword, name="cab.changePassword"),
    url(r'^change/$', cab.views.changeItem, name="cab.changeItem"),
    url(r'^changeDelFoto/$', cab.views.changeDelFoto, name="cab.changeDelFoto"),
    url(r'^changeAddFoto/$', cab.views.changeAddFoto, name="cab.changeAddFoto"),
    url(r'^changeTags/$', cab.views.changeTags, name="cab.changeTags"),
    url(r'^changeLibrary/$', cab.views.changeLibrary, name="cab.changeLibrary"),
    url(r'^changeInform/$', cab.views.changeInform, name="cab.changeInform"),
    url(r'^changeDelFile/$', cab.views.changeDelFile, name="cab.changeDelFile"),
    #url(r'^changeAddFile/$', cab.views.changeAddFile, name="cab.changeAddFile"),
    url(r'^changeAddFileSave/$', cab.views.changeAddFileSave, name="cab.changeAddFileSave"),
)

catalog/urls.py
from django.conf.urls import patterns, url
from catalog import views

urlpatterns = patterns('',
                       # ex: /cab Klients/
                       url(r'^$', views.main, name='catalog_main'),
                       url(r'^[0-9]*[/]+$', views.itemHtml, name='catalog_item'),
                       url(r'^libraries/$', views.libraries, name='libraries'),
                       url(r'^librarieslist/(?P<id>\d+)/$', views.libraries_detail, name='librariesdetail'),
                       url(r'^itemview/(?P<id>\d+)/$', views.itemHtmlFile, name='item_view_file'),
                       url(r'^viewfile/(?P<id>\d+)/$', views.showFile, name='showFile'),
            )

testSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
import cab.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('dashboard.urls')),
    url(r'^profile/', include('cab.urls')),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^statistic/', include('statistic.urls')),
    url(r'^admins/', include('staff.urls', namespace="staff")),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'},
                           name='auth_login'),
    url(r'^logout/$', cab.views.cab_logout, name='auth_logout'),
    url(r'^register/$', cab.views.register, name='auth_register'),
    url(r'^forgot/$', cab.views.forgotPassword, name='auth_forgotPassword'),
    url(r'^about/$', include('about.urls')),
]

about/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

cab/models.py
#coding: utf8
from __future__ import unicode_literals
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import BaseUserManager
from django.db import models


class UserManager(BaseUserManager):

    def create_user(self, email, password=None, lastname="", firstname=""):
        if not email:
            raise ValueError('Email непременно должен быть указан')
        email=UserManager.normalize_email(email)
        user = self.model( 
            email=email
        )
        

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email, password)
        user.is_admin = True
        user.save(using=self._db)
        return user


class ExtUser(AbstractBaseUser, PermissionsMixin):
    
    email = models.EmailField(
        '',
        max_length=255,
        unique=True,
        db_index=True
    )

    avatar = models.CharField(max_length=250)
    
    forgotKey = models.CharField(max_length=150)
    
    firstname = models.CharField(
        '',
        max_length=40,
        null=True,
        blank=True
    )
    lastname = models.CharField(
        '',
        max_length=40,
        null=True,
        blank=True
    )
    date_of_birth = models.DateField(
        'Date birthday',
        auto_now_add=True,
        null=True,
        blank=True
    )
    register_date = models.DateField(
        'Date register',
        auto_now_add=True
    )
    is_active = models.BooleanField(
        'Activate',
        default=True
    )
    is_admin = models.BooleanField(
        'Superuser',
        default=False
    )
    
    
    def createUserForViews(self, email, password, lastname, firstname):
        self.email = UserManager.normalize_email(email)
        self.password = UserManager.set_password(password)
        self.lastname = lastname
        self.firstname = firstname
        return None
        
    
    # Этот метод обязательно должен быть определён
    def get_full_name(self):
        return self.email

    # Требуется для админки
    @property
    def is_staff(self):
        return self.is_admin

    def get_short_name(self):
        return self.email

    def __str__(self):
        return self.email

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

catalog/models.py
    # coding: utf-8
from __future__ import unicode_literals
import datetime
from django.db import models
from cab.models import ExtUser
from django.core.urlresolvers import reverse


class fotos(models.Model):
    name = models.CharField(max_length=200)
    path = models.FileField(
        upload_to='media/fotos/', blank=True, null=True    
    )

class Libraries(models.Model):
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ForeignKey(fotos)
    
    def __unicode__(self):
        return self.name


class item(models.Model):
    name = models.CharField(max_length=100)
    date_published = models.DateTimeField(default=datetime.datetime.now())
    main_foto = models.ForeignKey(fotos)
    foto = models.TextField() # CSV format ';' values=[id_f, id_f, id_f]
    information = models.TextField()
    views = models.IntegerField(default=0)
    tags = models.TextField() # CSV format ';' values=[tag, tag, tag]
    user = models.ForeignKey(ExtUser)
    library = models.ForeignKey(Libraries, null=True, blank=True)
    
    
class like(models.Model):
    user = models.ForeignKey(ExtUser)
    item = models.ForeignKey(item)
    
    
class file(models.Model):
    name = models.CharField(max_length=150)
    dowloads = models.IntegerField(default=0)
    size = models.FloatField(default=0.0)
    date_published = models.DateTimeField(
        default=datetime.datetime.now()    
    )
    f = models.FileField(
        upload_to='media/files/', blank=True, null=True 
    )
    item = models.ForeignKey(item)
    
class Categories(models.Model):
    name = models.CharField(max_length=220)
    created_at = models.DateTimeField(auto_now_add=True)
    url = models.URLField(default="http://www.google.com")
    
    def __unicode__(self):
        return "{}".format(self.name)

dashboard/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

about/views.py
#coding: utf8
from django.shortcuts import render
from catalog.models import Categories



def main(request):
    categories = Categories.objects.all()
    return render(request, "about.html", {'categories': categories})

catalog/views.py
# coding: utf-8
import datetime
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.contrib.auth import logout
from catalog.models import item, fotos, file, like, Categories, Libraries
from django.http import JsonResponse
import json
from django.db.models import Q
from cab.models import ExtUser


def main(request):
    items = item.objects.all().order_by('-date_published')
    download = False
    if items.count() > 12:
        download=True
    lik = []
    items = items[:12]
    for i in items:
        lik.append([i.id, like.objects.filter(item=i).count()])
    categories = Categories.objects.all()
    return render(request, "catalog.html", {'items': items, 'likes':lik, 'download':download, 'categories': categories})
    
    
def itemHtml(request):
    categories = Categories.objects.all()
    try:
        id = request.path[request.path.find('/')+1:]
        id = id[id.find('/')+1:]
        id = id[:id.find('/')]
        it = item.objects.select_related().get(id=int(id))
        it.views += 1
        it.main_foto.name = it.main_foto.name.replace('media/','static/')
        it.save()
        #i.main_foto.save()
        f = it.foto.replace('media','static').split(';')
        files = file.objects.select_related().filter(item=it)
        for i in files:
            i.f.name = i.f.name.replace('media/', 'static/')
            #i.f.save()
            
        lik = like.objects.filter(item=it).count()
        #tags = it.tags
        return render(request, 'item.html', {
            'item':it,
            'f':f[:len(f)-1],
            'files': files,
            'like': lik,
            'tags':it.tags.split(';'),
            'categories': categories,
        })
    except:
        raise Http404


def libraries(request):
    categories = Categories.objects.all()
    libraries_all = Libraries.objects.all()
    return render(request, 'libraries.html', {"libraries_all": libraries_all, 'categories': categories})


def libraries_detail(request, id):
    categories = Categories.objects.all()
    library = Libraries.objects.get(id=id)
    items = library.item_set.all()
    lik = []
    for i in items:
        lik.append([i.id, like.objects.filter(item=i).count()])
    return render(
        request, 'items.html',
        {'items': items, 'likes': lik, 'categories': categories})


def showFile(request, id):
    _file = get_object_or_404(file, id=id)
    categories = Categories.objects.all()
    if _file.name.endswith('.stl') or _file.name.endswith('.STL'):
        path = _file.name
        return render(request, 'stl_file.html', {'path': path, 'categories': categories})
    if _file.name.endswith('.x3d') or _file.name.endswith('.X3D'):
        path = _file.name
        return render(request, 'x3d_file.html', {'path': path, 'categories': categories})
    return render(request, 'invalid_file.html')



def itemHtmlFile(request, id):
    categories = Categories.objects.all()
    it = item.objects.select_related().get(id=id)
    f = it.foto.replace('media','static').split(';')
    files = file.objects.select_related().filter(item=it)
    for i in files:
        i.f.name = i.f.name.replace('media/', 'static/')
        lik = like.objects.filter(item=it).count()
    if 'file_id' in request.GET:
        file_id = request.GET['file_id']
        _file = get_object_or_404(file, id=file_id)
        if _file.name.endswith('.stl') or _file.name.endswith('.STL'):
            path = _file.name
            return render(request,
                    'item_stl_file.html',
                        {
                            'path': path,
                            'categories': categories,
                            'item':it,
                            'f':f[:len(f)-1],
                            'files': files,
                            'like': lik,
                            'tags':it.tags.split(';'),
                            'file_id': file_id
                        })
        if _file.name.endswith('.x3d') or _file.name.endswith('.X3D'):
            path = _file.name
            return render(request,
                'item_x3d_file.html',
                        {
                            'path': path,
                            'categories': categories,
                            'item':it,
                            'f':f[:len(f)-1],
                            'files': files,
                            'like': lik,
                            'tags':it.tags.split(';'),
                            'file_id': file_id
                        })
    return render(request, 'item.html', {
        'item':it,
        'f':f[:len(f)-1],
        'files': files,
        'like': lik,
        'tags':it.tags.split(';'),
        'categories': categories
    })

dashboard/views.py
from django.shortcuts import render
from catalog.models import Categories

def main(request):
    categories = Categories.objects.all()
    return render(request, "dashboard.html", {'categories': categories})

templates/base.html
{% load staticfiles %}
<html>
<head>
{% include "item/head.html" %}
{% block mycss %}
{% endblock %}
</head>

<body>
  
{% block header %}
  <header>
  </header>
{% endblock %}
<!--КОНЕЦ ШАПКИ-->

<div style="min-height:60%">
{% block content%}{% endblock %}
</div>

{% block footer %}
  <footer>
		<ul class="footer-social">
  		<li><a href="" target="_blank"><i class="fa fa-twitter"></i></a></li>
  		<li><a href="" target="_blank"><i class="fa fa-linkedin"></i></a></li>
  		<li><a href="" target="_blank"><i class="fa fa-instagram"></i></a></li>
  		<li><a href="" target="_blank"><i class="fa fa-facebook"></i></a></li>
  	</ul>
  	<p class="copy tac">The website is designed: BioBots © 2016 </p>
  </footer>
{% endblock %}

{% block scripts %}
{% include "item/scripts.html" %}
{% endblock %}


</body>
</html>

templates/dashboard.html
{% extends "base.html" %}
{% load staticfiles %}

{% block header %}
<header>
	<div class="container" style="padding:0px">
		<div class="row">
			<a href="/" class="logo">
			    <img src="{% static 'images/logo.png'%}" alt="" />
			 </a>
            <div class="home-banner-inner col-sm-3" style="padding:0px; margin-left:10px">
    			<form role="search" class="form-search" method="get" id="searchform" action="{% url 'search' %}">
            		<div class="input-group">
            			<input style="height:inherit;width:100%" type="text" class="form-control" placeholder="Enter a Search Item" value="" name="s" id="s">	
            			<span class="input-group-btn">
            				<button style="height:100%" type="submit" class="banner-btn btn-append"><i class="fa fa-search fa- "></i></button>
            			</span>
            			<input type="hidden" value="incsub_wiki" name="post_type" id="post_type">
            		</div>
            	</form>
        	</div>
			<ul id="menu-test" class="mainNav">
			    <li id="menu-item-7" class="first-menu-item menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-7">
    			    <a href="/">
    			        dashboard
    		        </a>
    	        </li>
                <li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                    <!--<a href="/catalog">
                        EXPLORE
                    </a>-->
                        <a tabindex="-1" href="#">EXPLORE</a>
                        <ul class="dropdown-menu" style="left:100; margin-top: 26px;">
                            {% for category in categories %}
                            <li style="text-align:center">
                                <a href="{{ category.url }}">
                                    {{ category }}
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                </li>
                <li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                    <a href="/about">
                        About us
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                    <a href="/profile">
                        Profile / Items
                    </a>
                </li>
                <li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                    <a href="/logout">
                        logout
                    </a>
                </li>
                {% else %}
                <li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                    <a href="/login">Join / Sign in</a>
                </li>
                {% endif %}
            </ul>
			<button id="showLeft"><i class="fa fa-bars open-nav"></i> <i class="fa fa-times close-nav"></i></button>
			<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left mobile" id="cbp-spmenu-s1">
				<h3>Menu</h3>
				<ul id="menu-test-1" class="mobileNav">
				    <li class="first-menu-item menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-7">
				        <a href="/">
				            dashboard
			            </a>
		            </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                        <a href="/catalog">
                            EXPLORE
                        </a>
                    </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                        <a href="/about">
                            About us
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                        <a href="/profile">
                            Profile / Items
                        </a>
                    </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                        <a href="/logout">
                            logout
                        </a>
                    </li>
                    {% else %}
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                        <a href="/login">Join / Sign in</a>
                    </li>
                    {% endif %}
                </ul>			
            </nav>
			
		</div>
	</div>
</header>
{% endblock %}


{% block content %}
    <section id="home-hero" style="background:url(https://d3tv8xdpluq3qf.cloudfront.net/wp-content/uploads/2015/07/banner-home.jpg) no-repeat center center;-webkit-background-size: cover;-moz-background-size: cover;-o-background-size: cover;background-size: cover;position:relative;">
		<div class="home-banner-wrap">
			<div class="home-banner-inner">
				<h1 class="divider divider-top divider-lrg divider-red">Test Page for testing work python and django</h1>
				<p style="color:red">If you see it, everything means works normally. Be not frightened, this page so far in development.</p>
			</div>
		</div>
		<div class="intro-arrow animated bounce"><i class="fa fa-chevron-down"></i></div>
	</section>

{% endblock %}

templates/register.html
{% extends "base.html" %}
{% load staticfiles %}


{% block header %}
<header>
	<div class="container" style="padding:0px">
		<div class="row">
			<a href="/" class="logo">
			    <img src="{% static 'images/logo.png'%}" alt="" />
			 </a>
            <div class="home-banner-inner col-sm-3" style="padding:0px; margin-left:10px">
    			<form role="search" class="form-search" method="get" id="searchform" action="{% url 'search' %}">
            		<div class="input-group">
            			<input style="height:inherit;width:100%" type="text" class="form-control" placeholder="Enter a Search Item" value="" name="s" id="s">	
            			<span class="input-group-btn">
            				<button style="height:100%" type="submit" class="banner-btn btn-append"><i class="fa fa-search fa- "></i></button>
            			</span>
            			<input type="hidden" value="incsub_wiki" name="post_type" id="post_type">
            		</div>
            	</form>
        	</div>
			<ul id="menu-test" class="mainNav">
			    <li id="menu-item-7" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
    			    <a href="/">
    			        dashboard
    		        </a>
    	        </li>
                <li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                    <a href="/catalog">
                        EXPLORE
                    </a>
                </li>
                <li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                    <a href="/about">
                        About us
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                    <a href="/profile">
                        Profile / Items
                    </a>
                </li>
                <li id="menu-item-8" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                    <a href="/logout">
                        logout
                    </a>
                </li>
                {% else %}
                <li id="menu-item-8" class="first-menu-item menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-7">
                    <a href="/login">Join / Sign in</a>
                </li>
                {% endif %}
            </ul>
			<button id="showLeft"><i class="fa fa-bars open-nav"></i> <i class="fa fa-times close-nav"></i></button>
			<nav class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left mobile" id="cbp-spmenu-s1">
				<h3>Menu</h3>
				<ul id="menu-test-1" class="mobileNav">
				    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
				        <a href="/">
				            dashboard
			            </a>
		            </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                        <a href="/catalog">
                            EXPLORE
                        </a>
                    </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                        <a href="/about">
                            About us
                        </a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                        <a href="/profile">
                            Profile / Items
                        </a>
                    </li>
                    <li class="menu-item menu-item-type-post_type menu-item-object-page menu-item-8">
                        <a href="/logout">
                            logout
                        </a>
                    </li>
                    {% else %}
                    <li class="first-menu-item menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-7">
                        <a href="/login">Sign in / Join</a>
                    </li>
                    {% endif %}
                </ul>			
            </nav>
			
		</div>
	</div>
</header>
{% endblock %}


{% block content %}
    
    <div class="">
    <a class="hiddenanchor" id="toregister"></a>
    <a class="hiddenanchor" id="tologin"></a>

    <div id="wrapper">
      <div id="login" class="animate form">
        <section class="login_content" style="width:50%; margin:0 auto">
          <form method="post" action="{% url 'cab.registerPost' %}">
              {% csrf_token %}
              </br>
              <center>
            <h2>Register With </h2>
			    <img src="{% static 'images/logo.png'%}" alt="" />
			 </a> </center>
            </br>
            {{form}}
            <!--<div style="margin:10px; padding:10px;">
              <input style="height:40px" id="id_firstname" type="text" class="form-control" placeholder="Firstname" maxlength="150" name="firstname" required="" />
            </div>
            <div style="margin:10px; padding:10px;">
              <input style="height:40px" id="id_lastname" type="text" class="form-control" placeholder="Lastname" maxlength="150" name="lastname" required="" />
            </div>
            <div style="margin:10px; padding:10px;">
              <input style="height:40px" id="id_email" type="text" class="form-control" placeholder="E-mail" maxlength="150" name="email" required="" />
            </div>
            <div style="margin:10px; padding:10px;">
              <input style="height:40px" name="password" type="password" id="id_password" class="form-control" placeholder="Password" required="" />
            </div>
            <div style="margin:10px; padding:10px;">
              <input style="height:40px" name="password2" type="password" id="id_password2" class="form-control" placeholder="Repeat password" required="" />
            </div>-->
            </br>
            <h5><span style="color:#FF0000">Please Note All Fields With (*) Are Required </h5>
            </br>
            <div class="row">
                <div class="col-sm-4"></div>
                <div class="col-sm-4">
                    <input style="margin: 0px;width: 100%;height: 2em;line-height:1em" class="btn btn-default submit" type="submit" value="Create an account Now"/>
                </div>
                <!--<div class="col-sm-4">
                  <a href="/login" style="height: 2em;line-height:1em" class="btn btn-info">New To Biobot</a>
                </div>-->
              <div class="col-sm-4"></div>
            </div><!--
            <div class="clearfix"></div>
            <div class="separator">

              <div class="clearfix"></div>
              <br />

            </div>-->
            
          </form>
          <!-- form -->
         
        </section>
        <!-- content -->
      </div>

    </div>
  </div>    

{% endblock %}